### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by r4f4** [modularity-modules/varnish#1]
package: ntsysv-1.8-1.module_f14f127f.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     libnewt.so.0.52()(64bit)
     libnewt.so.0.52(NEWT_0.52)(64bit)

ntsysv is part of chkconfig. I don't think chkconfig should be listed in varnish, since it's already included by base-runtime.

**Comment by TomasTomecek** [comment]
I assume that chkconfig got included when it wasn't present in BRT. Can fix!

**Comment by TomasTomecek** [comment]
fixed: http://pkgs.fedoraproject.org/cgit/modules/varnish.git/commit/?h=f26&id=b073ba748b8b8ef74bb59722753fb09dae1f030f

I wasn't able to build container-runtime today, won't try varnish.

**Comment by r4f4** [comment]
Thank you for the fix. We'll close the issue when we can confirm the build is working.

**Comment by TomasTomecek** [comment]
```
ttomecek's build #659 of varnish-f26 is in the "ready" state (koji tag: "module-d3b631c6aaaf9606")
```

can we close?

**Comment by r4f4** [comment]
Thank you for the fix.

**Comment by TomasTomecek** [comment]
no, thank you for finding the issues

**Comment by r4f4** [comment]
Commenting here because I don't know if it is that important. varnish includes `util-linux` which is already part of base-runtime.

**Comment by TomasTomecek** [comment]
removed and submitted a new build:

```
ttomecek's build #703 of varnish-f26 is in the "wait" state
```

**Comment by TomasTomecek** [comment]
Rafael, it should be okay now:

```
ttomecek's build #703 of varnish-f26 is in the "ready" state (koji tag: "module-a0e42c6d717ea5f3")
```

Thank you for discovering the issue! Can't wait when we have an automation for this in-place.
